# Generated by Django 3.0.4 on 2020-04-05 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200405_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprop',
            name='durée_util',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='etat_achat',
            field=models.CharField(choices=[('NEUF', 'NEUF'), ('DEUXIEME MAIN', 'DEUXIEME MAIN'), ('OCCASION', 'OCCASION'), ('INCONU', 'INCONU')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='etat_actuel',
            field=models.CharField(choices=[('NEUF', 'NEUF'), ('BON ETAT', 'BON ETAT'), ('MOYEN', 'MOYEN'), ('MEDIOCRE', 'MEDIOCRE'), ('TRES DEGRADE', 'TRES DEGRADE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 5, 9, 38, 5, 884256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postsearch',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 5, 9, 38, 5, 885284, tzinfo=utc)),
        ),
    ]
