# Generated by Django 3.0.4 on 2020-04-06 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200405_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postprop',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 6, 7, 55, 22, 547347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postsearch',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 6, 7, 55, 22, 548567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='dexcription',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
