# Generated by Django 3.0.4 on 2020-05-07 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200503_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprop',
            name='l_descrip',
            field=models.CharField(default='128 Go de Stockage', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postprop',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 7, 15, 27, 40, 132321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postsearch',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 7, 15, 27, 40, 133234, tzinfo=utc)),
        ),
    ]
