# Generated by Django 3.0.4 on 2020-05-15 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200507_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100)),
                ('date', models.DateField(verbose_name=datetime.datetime(2020, 5, 15, 20, 37, 0, 826955, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='postprop',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 15, 20, 37, 0, 824296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postsearch',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 15, 20, 37, 0, 825275, tzinfo=utc)),
        ),
    ]
