# Generated by Django 3.0.4 on 2020-06-11 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20200611_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprop',
            name='image4',
            field=models.ImageField(blank=True, default='not-found.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 9, 45, 44, 956347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='image2',
            field=models.ImageField(blank=True, default='not-found.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='image3',
            field=models.ImageField(blank=True, default='not-found.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postprop',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 11, 9, 45, 44, 953809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postsearch',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 11, 9, 45, 44, 954825, tzinfo=utc)),
        ),
    ]
